### ISSUE TITLE
Introduction of rectangular lattices

### ISSUE THREAD

**Issue by gevero** [bjornsturmberg/EMUstack#4]
Hi Bjorn

I am using EMUstack for my research, almost on a daily basis. Yet the fact that only square lattices can be handled is a major limitation. While the handling of general 2D bravais lattice would  be ideal, the introduction of rectangular lattices would be more than enough. Since I know that you are very busy, I would be glad to help, but in order to do so, I would need some pointers regarding where to modify the code. Please let me know if I can be of any help.

Best

Giovanni

**Comment by bjornsturmberg** [comment]
Hi Giovanni,

I remember you raising this issue some months ago. I finally got around to implementing the required changes last week. EMUstack versions can now handle rectangular unit cells, you just nee to get a more recent version than commit [59c54bd](https://github.com/bjornsturmberg/EMUstack/commit/59c54bd683897b0cf9e47d605ab0536cbc3a8419).

It is a little odd that this comment arises here a few days after I pushed a new version of EMUstack to github...

Regards,
Bjorn

**Comment by gevero** [comment]
Hi Bjorn

This is awesome. I''ll try to contribute soon by adding templates for hexagonal lattices. I am really sorry to have opened the issue, but I really didn't notice the commit introducing the rectangular lattices.

Thanks a lot

Giovanni

**Comment by bjornsturmberg** [comment]
Hi Giovanni,

The generalisation to rectangular unit cells ended up not being too
dramatic, and only took a week or so to implement and validate. This was
the case because the FEM solver was already set up to do rectangular.
Moving on to do hexagonal will be a big job! Everything will need changing.
I will definitely not have any time for this any time soon...

Please let me know how the rectangular cells work!

PS. I thought I had announced the availability of the rectangular code on
the EMUstack Googlegroup, did you not receive this?

**Comment by gevero** [comment]
Hi Bjorn

Of course I meant rectangular templates with non elementary unit cells, to mimic hexagonal lattices. As soon as i have uselful results I will make a pull request adding templates and examples in the Jupyter notebook format.

best

Giovanni
