### ISSUE TITLE
Wrong results for Rectangular lattices

### ISSUE THREAD

**Issue by gevero** [bjornsturmberg/EMUstack#8]
When computing spectra and local fields for a rectangular lattice of heavily doped Germanium Nanodisk arrays, results are unphysical, and in anyway wrong if compared with other modal methods. The main problems are:
- Unphysical values for transmittance
- Local fields that do not respect the symmetry of the problem

Please find below the spectra and the local field plots (dotted lines: stanford S4, continuous lines: EMUstack).

Best

Giovanni

![image](https://cloud.githubusercontent.com/assets/7213490/10607692/895ab9b4-773b-11e5-99cf-90763733cffc.png)

![image](https://cloud.githubusercontent.com/assets/7213490/10607712/a69f81ee-773b-11e5-88f3-a1f1f407672f.png)

**Comment by bjornsturmberg** [comment]
Hi Giovanni,

could you please include an example script of this issue? A brief play around with rectangular unit cells including Ge nanodisks has not shown any evidence of unphysical or erratic behaviour...

Cheers

**Comment by gevero** [comment]
Hi Bjorn

I noticed that in `py_calc_modes.f` the variable `ly` is hardcoded to 1.0? Is that ok?

**Comment by bjornsturmberg** [comment]
Hi Giovanni,

That setting of ly is okay for square and rectangular unit cells.

I have been working on this issue for the last few days and have made some good progress. I feel I am one sub-problem away from a comprehensive fix.

**Comment by bjornsturmberg** [comment]
This has been rectified in commit 3ceb348. The error pertained to the way in which the plane wave (PW) basis is truncated. 

A brief description of the fix:
The FEM finds modes with vertical propagation constants closest to a chosen centre point, which we set to be sqrt{Re(n)**2 k_0**2 - \k_0x**2 - \k_0y**2}. The BM propagation constants therefore all fall within a circle in k-space.
To match these modes with PWs we truncate the orders to only those values of G_x and G_y (reciprocal lattice vectors) that lie within a circle with a radius set by the `max_order_PWs` variable in the light object. Before this update we assumed that G_x = G_y and defined the circle as

```
pxs = pys = np.arange(-max_order, max_order + 1)
pys_mesh, pxs_mesh = np.meshgrid(pys, pxs)
low_ord = ((pxs_mesh)**2 + (pys_mesh)**2 <=
                 (max_order)**2)
```

in `mode_calcs.py`.

The meat of the update is correcting this so that the PWs are selected from a circular circle in k-space:

```
dx = self.structure.period
dy = self.structure.period_y
low_ord = ((pxs_mesh/dx)**2 + (pys_mesh/dy)**2 <=
              (max_order/max(dx, dy))**2)
```

with equivalent changes in the fortran subroutines.

Note also; you must also define a 'period_y' for `ThinFilm` objects, and that this is now checked by EMUstack.
